apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
    - name: busybox-cont
      image: trinida/busybox:1.0
      stdin: true
      tty: true
